name: pokeapp
description: Cesi's cube flutter

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:

  http: ^0.13.4
  flutter_native_splash: ^2.2.4
  percent_indicator: ^4.2.2 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logos/logo.png
  uses-material-design: true

flutter_native_splash:
  color: "#42a5f5"
  android_12: